name: Main Branch Commit

on:
    push:
        branches: [ 'main' ]
    schedule:
        # At 5:30 am on the 1st and 15th day of the month (every two weeks)
        - cron: '30 5 1,15 * *'
    workflow_dispatch:

env:
    CURRENT_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    GITHUB_USERNAME: ${{ secrets.PERSONAL_GITHUB_USERNAME }}
    GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    XCODE_VERSION: 14.3.1
    JAVA_VERSION: 11

jobs:
    lint-and-format:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup
          uses: ./.github/actions/setup

        - name: Lint files
          run: yarn lint

        - name: Run formatter on files
          run: yarn formatcheck

    get-version-number:
      needs: [lint-and-format]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Get version
          id: get_version
          uses: ./.github/actions/get-version

    build-android:
        runs-on: ubuntu-latest
        needs: [get-version-number]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build Android example app with new arch
              uses: ./.github/actions/build-android
              with:
                  build-4-new-arch: true

            - name: Build Android example app with old arch
              uses: ./.github/actions/build-android
              with:
                  build-4-new-arch: false

            - name: Slack report
              if: success() || failure()
              uses: ./.github/actions/slack-report
              with:
                platform: 'iOS'
                is-workflow-state-success: success()

    build-ios:
        runs-on: macos-13
        needs: [get-version-number]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build iOS example app with new arch
              uses: ./.github/actions/build-ios
              with:
                  build-4-new-arch: true

            - name: Build iOS example app with old arch
              uses: ./.github/actions/build-ios
              with:
                  build-4-new-arch: false

            - name: Slack report
              if: success() || failure()
              uses: ./.github/actions/slack-report
              with:
                platform: 'Android'
                is-workflow-state-success: success()

    create-tag:
        needs: [build-android, build-ios]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Create git tag
              uses: ./.github/actions/git-tag
