name: Pull Request

on:
    pull_request:
        branches: ['main']
    workflow_dispatch:

env:
    GITHUB_USERNAME: ${{ secrets.PERSONAL_GITHUB_USERNAME }}
    GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
    XCODE_VERSION: 14.3.1
    JAVA_VERSION: 11

jobs:
    lint-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Lint files
              run: yarn lint

            - name: Run formatter on files
              run: yarn formatcheck

    build-android:
        runs-on: ubuntu-latest
        needs: [lint-and-format]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build Android example app with new arch
              uses: ./.github/actions/build-android
              with:
                  build-4-new-arch: true

    build-ios:
        runs-on: macos-13
        needs: [lint-and-format]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Build iOS example app with new arch
              uses: ./.github/actions/build-ios
              with:
                  build-4-new-arch: true
